source "https://rubygems.org"

gem "rails", "4.2.6"
group :development, :test do
  gem "byebug" # Comes standard with Rails
  gem "sqlite3" # Remove this when you choose a production database
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem "web-console", "~> 2.0"
end
