source "https://rubygems.org"

gem "rails", "5.1.0"
group :development, :test do
  gem "byebug" # Comes standard with Rails
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem "web-console", "~> 2.0"
  gem 'listen', '~> 3.1', '>= 3.1.5'
end
